import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dye } from '@0xkahi/cli-dye';
import { $ } from 'bun';
import { VAULT_CACHE_FOLDER } from '../../constants';
import type { CommandStrategy } from '../../utils/commander/command-strategy';
import { PathUtil } from '../../utils/path.util';
import { VaultCli } from '../../utils/vault-cli.util';

interface BundleHashMap {
  generatedTimestamp: string;
  bundles: Record<string, string>;
}

type BundleSyncOptions = {
  reset?: boolean;
};

export class BundleSyncCommand implements CommandStrategy {
  readonly config = {
    name: 'sync',
    description: 'Sync All Knowledge Bundles And Generate A Hash Map',
    options: [{ flag: '--reset', description: 'remove the generated hash map and sync tasklist' }],
  };

  async execute({ reset }: BundleSyncOptions): Promise<void> {
    const vaultPath = await VaultCli.getVaultPath();

    const cachePath = `${VAULT_CACHE_FOLDER}/bundles`;
    const fullCachePath = `${vaultPath}/${cachePath}`;

    await mkdir(fullCachePath, { recursive: true });

    const currentHashMap = PathUtil.findFile(`${fullCachePath}/hash_map.json`);
    if (!currentHashMap.exists) {
      await writeFile(currentHashMap.path, `${JSON.stringify({}, null, 2)}\n`);
    }

    const bundles = await VaultCli.getBundleFolders();
    const bundleHashMap = await this.getBundleHashMap(bundles);
    const outOfSyncBundles = await this.getOutOfSyncBundles(currentHashMap.path, bundleHashMap);

    const dontGenerateFiles = reset || outOfSyncBundles.length === 0;

    const generatedHashMap = PathUtil.findFile(`${fullCachePath}/generated_hash_map.json`);
    if (!generatedHashMap.exists && !dontGenerateFiles) {
      await this.generateNewHashMap(generatedHashMap.path, bundleHashMap);
    }

    const taskPath = `${cachePath}/task.md`;
    const syncTask = PathUtil.findFile(`${vaultPath}/${taskPath}`);
    if (!syncTask.exists && !dontGenerateFiles) {
      await this.generateSyncTasks(syncTask.path, outOfSyncBundles);
    }

    let pendingCount = 0;
    let completedCount = 0;
    let ignoredCount = 0;
    if (reset === true) {
      await Promise.all([rm(generatedHashMap.path, { force: true }), rm(syncTask.path, { force: true })]);
    } else {
      // only get task count if sync task exists, as there is a slight delay between generating the task file
      // and obdian cli recognizing it and updating the task counts
      if (syncTask.exists) {
        pendingCount = await VaultCli.getTaskCount(taskPath, 'pending');
        completedCount = await VaultCli.getTaskCount(taskPath, 'completed');
        ignoredCount = await VaultCli.getTaskCount(taskPath, 'ignored');
      } else {
        pendingCount = outOfSyncBundles.length;
      }
    }

    const lines = [
      dye.bold(`Bundle Sync Manifest`),
      '',
      '════════════════════════════════════════════════════════════',
      dye.bold('Summary:'),
      ` ${dye.colorize('●', { fg: 'cyan' })} Knowledge Bundles: ${bundles.size} total, ${outOfSyncBundles.length} outOfSync`,
      ` ${dye.colorize('●', { fg: 'yellow' })} Pending Tasks: ${pendingCount} in progress`,
      ` ${dye.colorize('●', { fg: 'green' })} Completed Tasks: ${completedCount}`,
      ` ${dye.colorize('●', { fg: 'red' })} Ignored Tasks: ${ignoredCount}`,
      '',
      dye.colorize({ fg: 'brightBlue' }).bold('FilePaths'),
      '────────────────────────────────────────────────────────────',
      `currentHashMap: ${dye.colorize(currentHashMap.path, { fg: `brightCyan` })}`,
      `generatedHashMap: ${dye.colorize(generatedHashMap.path, { fg: `brightCyan` })}${dontGenerateFiles ? ' (not generated)' : ''}`,
      `taskList: ${dye.colorize(syncTask.path, { fg: `brightCyan` })} ${dontGenerateFiles ? ' (not generated)' : ''}`,
      '',
      '════════════════════════════════════════════════════════════',
    ];

    const output = lines.join('\n');
    console.log(output);
  }

  private async getOutOfSyncBundles(currentHashMapPath: string, bundleHashMap: Record<string, string>): Promise<string[]> {
    const bundles = Object.keys(bundleHashMap);

    const currentHashMapContent = await readFile(currentHashMapPath, 'utf-8');
    const currentBundleHashMap: Partial<BundleHashMap> = JSON.parse(currentHashMapContent);
    const currentHashMap = currentBundleHashMap?.bundles;
    if (!currentHashMap) {
      return bundles;
    }

    const outOfSyncBundles: string[] = [];
    for (const bundle of bundles) {
      const currentHash = currentHashMap[bundle];
      const newHash = bundleHashMap[bundle];
      if (currentHash !== newHash) {
        outOfSyncBundles.push(bundle);
      }
    }
    return outOfSyncBundles;
  }

  private async generateSyncTasks(path: string, outOfSyncBundles: string[]) {
    const lines = [
      '# Bundle Sync Tasks',
      '',
      'This file is generated by the sync command. and list potentially out of sync bundles',
      '',
      ...outOfSyncBundles.map((bundle, index) => `${index + 1}. [ ] ${bundle}`),
    ];

    await writeFile(path, lines.join('\n'));
  }

  private async generateNewHashMap(path: string, bundleHashMap: Record<string, string>) {
    const hashMap: BundleHashMap = {
      generatedTimestamp: new Date().toISOString(),
      bundles: bundleHashMap,
    };
    await writeFile(path, `${JSON.stringify(hashMap, null, 2)}\n`);
  }

  private async getBundleHashMap(bundles: Set<string>): Promise<Record<string, string>> {
    const bundleHashMap: Record<string, string> = {};
    for (const bundle of bundles) {
      const bundleData = await this.getBundleViewText(bundle);
      const bundleHash = createHash('md5').update(bundleData).digest('hex');
      bundleHashMap[bundle] = bundleHash;
    }
    return bundleHashMap;
  }

  private async getBundleViewText(bundle: string): Promise<string> {
    const shell = $`llw bundle view --bundle ${bundle}`;
    return (await shell.text()).trim();
  }
}
